[font]
size = 12.0

[font.normal]
family = "Monofur Nerd Font"
style = "Regular"

[window]
opacity = 0.9
live_config_reload = true

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true
