color0       #000000
color8       #9C9C9C
color1       #3B3B3B
color9       #3B3B3B
color2       #676767
color10      #676767
color3       #6A6A6A
color11      #6A6A6A
color4       #6D6D6D
color12      #6D6D6D
color5       #959595
color13      #959595
color6       #CFCFCF
color14      #CFCFCF
color7       #DEDFDF
color15      #DEDFDF