color0       #3E3D3C
color8       #A69E77
color1       #907E7B
color9       #907E7B
color2       #6C9B6E
color10      #6C9B6E
color3       #7F9594
color11      #7F9594
color4       #C49642
color12      #C49642
color5       #BDB99A
color13      #BDB99A
color6       #ECD467
color14      #ECD467
color7       #EDE1AA
color15      #EDE1AA