
$background = rgba(171216ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(352e33ff)

$inverse_primary = rgba(7e4e7cff)

$inverse_surface = rgba(ebdfe6ff)

$on_background = rgba(ebdfe6ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(4a204bff)

$on_primary_container = rgba(ffd6f9ff)

$on_primary_fixed = rgba(320935ff)

$on_primary_fixed_variant = rgba(643663ff)

$on_secondary = rgba(3c2b3bff)

$on_secondary_container = rgba(f6dbf0ff)

$on_secondary_fixed = rgba(261625ff)

$on_secondary_fixed_variant = rgba(544152ff)

$on_surface = rgba(ebdfe6ff)

$on_surface_variant = rgba(d0c3ccff)

$on_tertiary = rgba(4c261dff)

$on_tertiary_container = rgba(ffdad2ff)

$on_tertiary_fixed = rgba(33110aff)

$on_tertiary_fixed_variant = rgba(663b31ff)

$outline = rgba(998d96ff)

$outline_variant = rgba(4d444bff)

$primary = rgba(eeb4e9ff)

$primary_container = rgba(643663ff)

$primary_fixed = rgba(ffd6f9ff)

$primary_fixed_dim = rgba(eeb4e9ff)

$scrim = rgba(000000ff)

$secondary = rgba(d9bfd4ff)

$secondary_container = rgba(544152ff)

$secondary_fixed = rgba(f6dbf0ff)

$secondary_fixed_dim = rgba(d9bfd4ff)

$shadow = rgba(000000ff)

$source_color = rgba(e522f3ff)

$surface = rgba(171216ff)

$surface_bright = rgba(3e373cff)

$surface_container = rgba(241e23ff)

$surface_container_high = rgba(2e282dff)

$surface_container_highest = rgba(393338ff)

$surface_container_low = rgba(201a1eff)

$surface_container_lowest = rgba(120d11ff)

$surface_dim = rgba(171216ff)

$surface_tint = rgba(eeb4e9ff)

$surface_variant = rgba(4d444bff)

$tertiary = rgba(f6b8aaff)

$tertiary_container = rgba(663b31ff)

$tertiary_fixed = rgba(ffdad2ff)

$tertiary_fixed_dim = rgba(f6b8aaff)


