Net/ThemeName "Material-Palenight-BL"
Net/IconThemeName "Spectrum-Color-Dark-Icons"
Gtk/CursorThemeName "Bibata-Modern-Ice"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
